---
title: "Cantidad de colegios en la Región de la Araucanía (2005-2019)."
author: "Daniel Pailañir"
output: html_document
---
```{r, include = FALSE}
library(dplyr)
library(ggplot2)
library(gganimate)
library(sf)
library(haven)
library(gifski)
```

```{r, include = FALSE}
# importamos shape de region
region <- st_read("C:/Users/danie/Desktop/Proyectos/Mapa-Colegios/R09/comuna.shp")

# importamos ubicacion de colegios
colegios_araucania <- read_dta(
                    "C:/Users/danie/Desktop/Proyectos/Mapa-Colegios/Colegios/colegios_r9.dta")
```

```{r, echo = FALSE}
plot1 <- ggplot(data = region) + 
          geom_sf(aes(),
                  color = "black",
                  fill = "#99CCFF") + 
          geom_point(data = colegios_araucania,
                     aes(x = longitud, y = latitud),
                     color = "red",
                     size = 1.5) +
          transition_states(agno,
                            transition_length = 1,
                            state_length = 20) +
          labs(title = 'Year: {previous_state}') +
          theme_bw()

plot1

# Exportar (opcional)
# anim_save("mapa-colegios.gif", plot1, width = 600, height = 600)
```
